[versions]
sonarqube = "6.2.0.5505"
springBoot = "4.1.1"
springDependencyManagement = "1.1.7"
pitestPlugin = "1.15.0"
pitestJunit5 = "1.2.1"
junitBom = "5.10.0"
cucumber = "7.18.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite" }
pitest-junit5-plugin = { module = "org.pitest:pitest-junit5-plugin", version.ref = "pitestJunit5" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit-platform-engine = { module = "io.cucumber:cucumber-junit-platform-engine", version.ref = "cucumber" }

[plugins]
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
pitest = { id = "info.solidsoft.pitest", version.ref = "pitestPlugin" }
